# Step 2. Nodes Catalogue

Primer paso de la implementación de la base BDUNAM (debido a que ya se tiene la base de datos en formato csv).

Primero, se divide la base de datos en dos, según la fecha de los artículos escritos, para conformar los datos que en un futuro servirán como entrenamiento, prueba  y validacion. Se generan tres CSV: *UNAM_train_1988_2022.csv* y *UNAM_test_2024.csv* UNAM_val_2023.csv

Segundo, se selecciona el titulo y el autor, y se cuenta el número de veces que aparece cada autor (el numero de artículos que ha escrito). El resultado se almacena en *nodes_catalogue.csv*, y contiene el nombre de cada autor y el número de artículos que ha escrito.

In [126]:
import pandas as pd

In [127]:
import chardet

# Detectar encoding del archivo
with open("UNAM_Completo_Corregido.csv", "rb") as f:
    result = chardet.detect(f.read())
    encoding_detectado = result["encoding"]

In [128]:
print(encoding_detectado)

UTF-8-SIG

In [129]:
df_original = pd.read_csv('UNAM_Completo_Corregido.csv')

In [130]:
df_original

,indice,Titulo,Año,Autor_norm,Afiliacion1,Afiliacion2,ISBN,ISSN,Doi,URL,Area,Subarea,Keywords,Abstract
0,20521,4-Phenylcoumarin (4-PC) Glucoside from Exostem...,2022,Araceli Pérez Vásquez,Facultad de Química,NaN,NaN,1422-0067,https://doi.org/10.3390/ijms23063130,https://www.scopus.com/inward/record.uri?eid=2...,CC,NaN,5-o-β-d-glucopyranosyl-7-methoxy-3<sup>′</sup>...,The corrosion inhibition of 5-O-β-D-glucopyran...
1,20521,4-Phenylcoumarin (4-PC) Glucoside from Exostem...,2022,Francisco Javier Rodriguez Gomez,Facultad de Química,NaN,NaN,1422-0067,https://doi.org/10.3390/ijms23063130,https://www.scopus.com/inward/record.uri?eid=2...,CC,NaN,5-o-β-d-glucopyranosyl-7-methoxy-3<sup>′</sup>...,The corrosion inhibition of 5-O-β-D-glucopyran...
2,20521,4-Phenylcoumarin (4-PC) Glucoside from Exostem...,2022,Ignacio Alejandro Figueroa Vargas,Instituto de Investigaciones en Materiales,NaN,NaN,1422-0067,https://doi.org/10.3390/ijms23063130,https://www.scopus.com/inward/record.uri?eid=2...,CC,NaN,5-o-β-d-glucopyranosyl-7-methoxy-3<sup>′</sup>...,The corrosion inhibition of 5-O-β-D-glucopyran...
3,20176,A Camera-Based Remote Sensor for Physical Ther...,2024,Jose Antonio Marmolejo Saucedo,Facultad de Ingeniería,NaN,9.78E+12,2522-8595,https://doi.org/10.1007/978-3-031-34750-4_12,https://www.scopus.com/inward/record.uri?eid=2...,CC,NaN,"parkinson’s disease, physical therapy, remote ...",The present chapter shows a camera-based remot...
4,20176,A Camera-Based Remote Sensor for Physical Ther...,2024,Luis Jimenez Angeles,Facultad de Ingeniería,NaN,9.78E+12,2522-8595,https://doi.org/10.1007/978-3-031-34750-4_12,https://www.scopus.com/inward/record.uri?eid=2...,CC,NaN,"parkinson’s disease, physical therapy, remote ...",The present chapter shows a camera-based remot...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5250,20726,When are building blocks useful,2006,Jorge Fernando Cervantes Borja,Posgrado en Ciencia e Ingeniería de la Computa...,NaN,9780769527222;0769527221,NaN,10.1109/MICAI.2006.49,https://ieeexplore-ieee-org.pbidi.unam.mx:2443...,TC,Genetic and Evolutionary Computation,Genetic mutations;Predictive models;Nonlinear ...,There is still debate about as to how GAs work...
5251,20751,Why recombination should be adaptive,2010,Christopher Rhodes Stephens,Instituto de Ciencias Nucleares,Centro de Ciencias de la Complejidad,9.78E+12,NaN,10.1145/1830483.1830634,https://dl.acm.org/doi/abs/10.1145/1830483.183...,TC,Genetic and Evolutionary Computation,NaN,Crossover is the most complicated of the stand...
5252,20760,Wigner-ville distribution enhancement for 2D-f...,2003,Ernesto Rubio Acosta,Instituto de Investigaciones en Matemáticas Ap...,NaN,NaN,NaN,10.1109/ULTSYM.2003.1293160,https://ieeexplore-ieee-org.pbidi.unam.mx:2443...,TC,Geoscience,flaw detection;acoustic signal processing;time...,A transmitted wide beam of ultrasonic pulse is...
5253,20760,Wigner-ville distribution enhancement for 2D-f...,2003,Lucía Medina Gómez,Instituto de Investigaciones en Matemáticas Ap...,NaN,NaN,NaN,10.1109/ULTSYM.2003.1293160,https://ieeexplore-ieee-org.pbidi.unam.mx:2443...,TC,Geoscience,flaw detection;acoustic signal processing;time...,A transmitted wide beam of ultrasonic pulse is...
5254,20762,Wind field reproduction using neural networks ...,2007,Neftalí Rodríguez Cuevas,Instituto de Ingeniería,NaN,NaN,NaN,10.1016/j.engstruct.2006.08.024,https://www-sciencedirect-com.pbidi.unam.mx:24...,TC,Artificial Intelligence,Wind simulation; Neural networks; Eigenfaces f...,A procedure based on the use of artificial neu...

In [131]:
# numero de registros totales
df_original.shape[0]

5255

## Separar Base de Datos por fechas

70

Datos para entrenamiento: 2000 - 2022 70%  

Datos para validación: 2023   15 %

Datos para test: 2024  15%

In [132]:
#número de artículos por año
#df_original['Año'].value_counts()

In [133]:
#CSV con los datos de entrenamiento desde 2000 a 2020 
df_2000_2020 = df_original[df_original['Año'] < 2021]
df_2000_2020.reset_index(drop = True)
df_2000_2020.to_csv('UNAM_training_2000_2020.csv',index=False)
df_2000_2020.shape

(2788, 14)

In [134]:
2788/5255 
#53% para entrenamiento

0.5305423406279733

In [135]:
#CSV con los datos de validacion desde 2019 a 2021 si fuera 15% deberia ser 
df_2021_2022 = df_original[(df_original['Año'] >= 2021) & (df_original['Año'] < 2023)] 
df_2021_2022.reset_index(drop=True, inplace=True)
df_2021_2022.to_csv('UNAM_val_2021_2022.csv', index=False)
print(df_2021_2022.shape)

(1572, 14)

In [136]:
1572/5255
# 30% de validación

0.29914367269267367

In [137]:
#CSV con los datos de test desde 2021 en adelante (2024)
df_2023_2024 = df_original[df_original['Año'] >= 2023]
df_2023_2024.reset_index(drop = True)
df_2023_2024.to_csv('UNAM_test_2023_2024.csv',index=False)
df_2023_2024.shape

(895, 14)

In [138]:
895/5255
# 17% de test

0.170313986679353

## Nodes Catalogue

Se utilizan todos los autores para generar el Nodes Catalogue

In [139]:
# Obtener solo el autor y el numero de articulos, ordenado por autor
df_original =df_original[['Titulo','Autor_norm']].groupby('Autor_norm',as_index=False).count()

In [140]:
#NO Separar solo autores con mas de 2 articulos no vamos a filtrar autores para que no disminuyan las muestras
# df_original = df_original[df_original['Titulo']>2]

In [141]:
#df_original = df_original.reset_index(drop=True)

In [142]:
df_original.to_csv('nodes_catalogue.csv',encoding='utf-8')

In [143]:
df_original

                         Autor_norm  Titulo
0                        A.  Bayona       1
1                          A.  Dutt       1
2                      A.  Galdámez       1
3                         A.  Román       1
4                  A.  Terán Franco       1
...                             ...     ...
1976         Ángel M.  García Reyes       1
1977            Ángel Martín Pendás       1
1978          Óscar Arana Hernández       2
1979  Óscar Arturo Fuentes  Mariles       1
1980                 Óscar Espinoza       1

[1981 rows x 2 columns]

In [144]:
# se obtuenen 1981 autores